schemaVersion: 2.0
timeout: 240

notify:
  pullRequestComment:
    postOnSuccess: false

machine:
  env:
    RUNTIME_JDK_VERSION: 11
    skipTest: false
    CODE_VERSION: $(./code_version.sh)
    GRADLE_LOG_LEVEL: INFO

jenkins:
  concurrentBuild: true
  maxConcurrentTotal: 8

reports:
  checkstyle: true
  pmd: true
  findbugs: true
  junit: true

pipelines:

# prb builds
- branchName: aiml-flink-1.4.x-release-prb
  build:
    template: buildozer:v4:prb

# publish pipelines
- branchName: aiml-flink-1.4.x-release
  build:
    template: buildozer:v4:publish
  package:
    release: true
    libraries:
    - publish:
      - repo: m2:oss-patched
  finally:
    radar:
      annotate: true
    tag:
      expression: ${CODE_VERSION}

- branchName: enumerator-metrics-preview
  build:
    template: buildozer:v4:publish
  package:
    release: true
    libraries:
      - publish:
          - repo: m2:oss-patched
  finally:
    radar:
      annotate: true
    tag:
      expression: ${CODE_VERSION}
